name: Firebase App Distribution

on:
  push:
    branches:
      - main # Or your release branch name
  workflow_dispatch: # Enable manual triggering

jobs:
    build-and-distribute:
      name: Build and Distribute to Firebase App Distribution
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Build Release APK
          run: ./gradlew assembleRelease
        - name: Sign Android release
          uses: r0adkll/sign-android-release@v1
          with:
            releaseDirectory: app/build/outputs/apk/release/
            signingKeyBase64: ${{ secrets.KEYSTORE }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
          env:
            BUILD_TOOLS_VERSION: "34.0.0"
        - name: Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{ secrets.FIREBASE_APP_ID }}
            token: ${{ secrets.FIREBASE_TOKEN }}
            groups: ${{ secrets.FIREBASE_TESTERS_GROUP }} # Optional
            file: app/build/outputs/apk/release/app-release-unsigned-signed.apk
            releaseNotes: "New release pushed from GitHub Actions"