import homework.classes.*

fun main() {
//    runExample1()
//    runExample2()
//    runExample3()
//    runExample4()
//    runExample5()
//    runExample6()
//    runExample7()
//    runExample8()
//    runExample9()
//    runExample10()
//    runExample11()
//    runExample12()
//    runExample13()
//    runExample14()
//    runExample15()
//    runExample16()
//    runExample17()
//    runExample18()

//    runHomework01()
//    runHomework02()
//    runHomework03()
//    runHomework04()
//    runHomework05()
//    runHomework06()
//    runHomework07()
//    runHomework08()
//    runHomework09()
//    runHomework10()
//    runHomework11()
//    runHomework12()
//    runHomework13()
//    runHomework14()
    runHomework15()
}

